#!/usr/bin/env bash
# Write fixtures/MANIFEST.md: which cala produced the seeds, what its own test
# suite reported, and per-table row counts. Called by generate.sh; can be
# re-run on its own from an existing fixtures/raw/cargo-test.log.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SEED_DIR="$HERE/seed"
TEST_LOG="$HERE/raw/cargo-test.log"

CALA_VERSION="${CALA_VERSION:-unknown}"
CALA_REV="${CALA_REV:-unknown}"
RUST_IMAGE="${RUST_IMAGE:-unknown}"
PG_IMAGE="${PG_IMAGE:-unknown}"
TEST_STATUS="${TEST_STATUS:-unknown}"

passed=$(grep -cE '^test .* \.\.\. ok$' "$TEST_LOG" || true)
failed=$(grep -cE '^test .* \.\.\. FAILED$' "$TEST_LOG" || true)

{
  echo "# Fixture provenance"
  echo
  echo "Generated by \`fixtures/generate.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "Nothing in \`seed/\` is hand-written: every row was inserted by cala-ledger's"
  echo "own code while its integration suite ran against a fresh Postgres."
  echo
  echo "| | |"
  echo "|---|---|"
  echo "| cala-ledger version | \`$CALA_VERSION\` |"
  echo "| cala commit | \`$CALA_REV\` |"
  echo "| rust image | \`$RUST_IMAGE\` |"
  echo "| postgres image | \`$PG_IMAGE\` |"
  echo "| cargo test exit status | \`$TEST_STATUS\` |"
  echo "| tests passed / failed | $passed / $failed |"
  echo
  if [[ "$failed" != "0" ]]; then
    echo "## Failed cala tests"
    echo
    echo "Listed for transparency. A failing test does not invalidate the dump: the"
    echo "rows come from whatever cala committed, and the warehouse tests decide"
    echo "whether those rows are consistent."
    echo
    echo '```'
    grep -E '^test .* \.\.\. FAILED$' "$TEST_LOG" || true
    echo '```'
    echo
  fi
  echo "## Row counts"
  echo
  echo "| table | rows |"
  echo "|---|---:|"
  for f in "$SEED_DIR"/*.csv; do
    t="$(basename "$f" .csv)"
    echo "| \`$t\` | $(($(wc -l < "$f") - 1)) |"
  done
} > "$HERE/MANIFEST.md"
echo "==> wrote $HERE/MANIFEST.md ($passed passed, $failed failed)"
